### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by oluwabajio** [lincollincol/HEIF-converter#2]
Thanks for this library.

But i get this error when i implement in my project.

 Process: heic.jpg.converter.heictojpgconverterapp, PID: 6189
    java.lang.RuntimeException: infe not implemented
        at linc.com.heifconverter.iso14496.part12.ItemInfoEntry.getContent(ItemInfoEntry.kt:27)
        at org.mp4parser.support.AbstractBox.verify(AbstractBox.java:193)
        at org.mp4parser.support.AbstractBox.parseDetails(AbstractBox.java:146)
        at linc.com.heifconverter.iso14496.part12.ItemInfoBox.parse(ItemInfoBox.kt:33)
        at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:116)
        at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
        at org.mp4parser.boxes.iso14496.part12.MetaBox.parse(MetaBox.java:107)
        at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:116)
        at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
        at org.mp4parser.IsoFile.<init>(IsoFile.java:57)
        at org.mp4parser.IsoFile.<init>(IsoFile.java:52)
        at linc.com.heifconverter.HeifReader.decodeByteArray(HeifReader.kt:129)
        at linc.com.heifconverter.HeifReader.decodeFile(HeifReader.kt:178)
        at linc.com.heifconverter.HeifReader.decodeStream(HeifReader.kt:243)
        at linc.com.heifconverter.HeifReader.decodeUrl(HeifReader.kt:262)
        at linc.com.heifconverter.HeifConverter$convert$2$1.invokeSuspend(HeifConverter.kt:140)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by lincollincol** [comment]
@oluwabajio Can you share more details about it? For example code or android version?

**Comment by oluwabajio** [comment]
Android version is 10, This was exactly the code i used.

 HeifConverter.useContext(requireActivity())
             .fromUrl("https://github.com/nokiatech/heif/raw/gh-pages/content/images/crowd_1440x960.heic")
            .withOutputFormat(HeifConverter.Format.PNG)
            .withOutputQuality(100)
            .saveFileWithName("Image_Certed_Name_2")
            .saveResultImage(true)
            .convert {
                println(it[HeifConverter.Key.IMAGE_PATH] as String)
                //  resultImage.setImageBitmap((it[HeifConverter.Key.BITMAP] as Bitmap))
            }

**Comment by oluwabajio** [comment]
Here is a blank project implementing this library, you can run it on your ide and check.
https://easyupload.io/sqyqlh

**Comment by lincollincol** [comment]
@oluwabajio Okay, I'll try to solve this problem.

**Comment by oluwabajio** [comment]
thanks, i would be expecting your response.

**Comment by lincollincol** [comment]
@oluwabajio Try new HEIF-Converter version 1.2

`implementation 'com.github.lincollincol:HEIF-converter:1.2'`

It works on my machine with this project -> https://easyupload.io/sqyqlh

**Comment by oluwabajio** [comment]
Works fine now. Thanks. You can close this issue.

**Comment by lincollincol** [comment]
@oluwabajio Good. Thank you for this bug report! Have a nice day!
