### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by wangshufu** [lincollincol/HEIF-converter#5]
Running in Android 10 is successful ,but Android 7.1.1 is failure
HeifConverter.useContext(this)
                .fromFile("/sdcard/nut/IMG_61072668.heic")
                .withOutputFormat(HeifConverter.Format.JPEG)
                .withOutputQuality(100)
                .saveFileWithName("Image_Converted_Name")
                .saveResultImage(true)
                .convert {
                    println(it[HeifConverter.Key.IMAGE_PATH] as String)
                    resultImage.setImageBitmap((it[HeifConverter.Key.BITMAP] as Bitmap))
                }

This file exists!!!

    java.lang.NoSuchMethodError: No virtual method limit(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
        at org.mp4parser.AbstractBoxParser.parseBox(AbstractBoxParser.java:84)
        at org.mp4parser.BasicContainer.initContainer(BasicContainer.java:107)
        at org.mp4parser.IsoFile.<init>(IsoFile.java:57)
        at org.mp4parser.IsoFile.<init>(IsoFile.java:52)
        at linc.com.heifconverter.HeifReader.decodeByteArray(HeifReader.kt:106)
        at linc.com.heifconverter.HeifReader.decodeFile(HeifReader.kt:150)
        at linc.com.heifconverter.HeifConverter$convert$2$1.invokeSuspend(HeifConverter.kt:139)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by lincollincol** [comment]
Hello @wangshufu, thank you for reporting this bug. I'll try to fix it soon!

**Comment by rizwankhanMiranshah** [comment]
private suspend fun renderHevcImageWithFormat(
        bitstream: ByteBuffer,
        info: ImageInfo,
        imageFormat: Int
    ): Bitmap {
        ImageReader.newInstance(
            info.size!!.width,
            info.size!!.height,
            imageFormat,
            1
        ).use { reader ->
            val bitmapDeferred = CoroutineScope(Dispatchers.Default).async {
                renderHevcImage(bitstream, info, reader.surface)
                var image: Image? = null

                return@async try {
                    image = try {
                        reader.acquireNextImage()
                    } catch (ex: UnsupportedOperationException) {
                        throw FormatFallbackException(ex)
                    }
                    when (image.format) {
                        ImageFormat.YUV_420_888, ImageFormat.YV12 -> convertYuv420ToBitmap(image)
                        ImageFormat.RGB_565 -> convertRgb565ToBitmap(image)
                        else -> throw RuntimeException("unsupported image format(" + image.format + ")")
                    }
                } finally {
                    image?.close()
                }
            }
            return@renderHevcImageWithFormat bitmapDeferred.await()
        }
    }

**Comment by rizwankhanMiranshah** [comment]
<img width="1115" alt="Screenshot 2021-03-09 at 12 37 36 AM" src="https://user-images.githubusercontent.com/17899060/110372251-e19fbf00-806f-11eb-8055-bd35e86e0e1c.png">
showing me this error when import in android studio

**Comment by AlexGolovach** [comment]
Hello, @lincollincol have you any updates about this problem?

**Comment by lincollincol** [comment]
Hello @AlexGolovach. Currently, I don't have enough time to fix it fast but I'm still looking for a solution at free time

**Comment by Vinny94051** [comment]
> <img alt="Screenshot 2021-03-09 at 12 37 36 AM" width="1115" src="https://user-images.githubusercontent.com/17899060/110372251-e19fbf00-806f-11eb-8055-bd35e86e0e1c.png">
> showing me this error when import in android studio
I have the same issue
